apiVersion: v2
name: alloy
description: alloy
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: k8s-monitoring
    version: 3.3.2
    repository: https://grafana.github.io/helm-charts
