---
# Source: cilium-config/templates/announce-everything.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  namespace: "cilium-config"
  name: announce-everything
spec:
  # No serviceSelector, apply to all.
  # No nodeSelector, many of these run on the control plane anyway.
  # nodeSelector:
  #   matchExpressions:
  #     - key: node-role.kubernetes.io/control-plane
  #       operator: DoesNotExist
  externalIPs: true
  loadBalancerIPs: true
---
# Source: cilium-config/templates/lb-external-ip-pool.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  namespace: "cilium-config"
  name: lb-externalip-pool
spec:
  blocks:
    - cidr: "placeholder"
