---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cilium-config:cilium.io/CiliumL2AnnouncementPolicy:cilium/announce-everything
  name: announce-everything
  namespace: cilium
spec:
  externalIPs: true
  loadBalancerIPs: true

---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: cilium-config:cilium.io/CiliumLoadBalancerIPPool:cilium/lb-externalip-pool
  name: lb-externalip-pool
  namespace: cilium
spec:
  blocks:
  - cidr: 10.0.193.0/24
