apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-notifications-secret
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: vaults/tiles-secrets/items/argocd-slack-token
