apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: google-oauth-secret
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: 'vaults/{{ required ".Values.vault_name is required" .Values.vault_name }}/items/argocd-google-oauth'
