{{- if .Values.grafana_integration_enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-apikey
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: 'vaults/{{ required ".Values.vault_name is required" .Values.vault_name }}/items/grafana-argocd-apikey'
{{- end }}
