apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  namespace: argocd
spec:
  description: '{{ required ".Values.cluster_name is required" .Values.cluster_name }} Project'
  sourceRepos:
    - https://github.com/symmatree/tiles.git
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    - https://charts.containeroo.ch
    - https://grafana.github.io/helm-charts
    - https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  # Allow creating all types of cluster-scoped resources...
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  # ...except CRDs because then cert-manager tries to nuke them.
  clusterResourceBlacklist:
    - group: "apiextensions.k8s.io/v1"
      kind: "CustomResourceDefinition"
  orphanedResources:
    warn: true
    ignore:
      # Argocd:
      # app-of-apps, we install directly:
      - kind: Application
        name: argocd-applications
      # Generated at runtime
      - kind: Secret
        name: argocd-initial-admin-secret
      # Generated at runtime
      - kind: Secret
        name: argocd-redis
      # cert-manager
      - kind: Secret
        name: cert-manager-webhook-ca
      - kind: Secret
        name: lets-encrypt-real
      - kind: Secret
        name: lets-encrypt-staging
