apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  namespace: argocd
spec:
  description: '{{ required ".Values.cluster_name is required" .Values.cluster_name }} Project'
  sourceRepos:
    - https://github.com/symmatree/tiles.git
    - https://kubernetes-csi.github.io/csi-driver-nfs
    - https://charts.containeroo.ch
    - https://grafana.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  # Allow creating all types of cluster-scoped resources...
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  # ...except CRDs because then cert-manager tries to nuke them.
  clusterResourceBlacklist:
    - group: "apiextensions.k8s.io/v1"
      kind: "CustomResourceDefinition"
  orphanedResources:
    warn: true
