apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gsa-mimir
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: vaults/{{ .Values.vault_name }}/items/{{ .Values.cluster_name }}-gsa-mimir
