apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: loki-data-source
  namespace: "{{ .Release.Namespace }}"
  labels:
    grafana_datasource: "1"
type: Opaque
spec:
  itemPath: vaults/{{ .Values.vault_name }}/items/{{ .Values.cluster_name }}-loki-tenant-auth
