apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: lb-externalip-pool
spec:
  blocks:
    - cidr: "{{ .Values.external_ip_cidr }}"
