apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odm
spec:
  project: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  source:
    repoURL: https://github.com/symmatree/tiles.git
    targetRevision: '{{ required ".Values.targetRevision is required" .Values.targetRevision }}'
    path: tanka
    plugin:
      env:
        - name: TK_ENV
          value: odm
      parameters:
        - name: cluster_name
          string: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
        - name: vault_name
          string: '{{ required ".Values.vault_name is required" .Values.vault_name }}'
        - name: app_settings
          map:
            webOdmIngressHost: 'odm.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com'
            nfs_server: '{{ required ".Values.nfs_server is required" .Values.nfs_server }}'
            datasets_nfs_path: '{{ required ".Values.datasets_nfs_path is required" .Values.datasets_nfs_path }}'
  destination:
    server: https://kubernetes.default.svc
    namespace: odm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/warn: baseline
