apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-mixin
  namespace: argocd
  labels:
    name: kubernetes-mixin
spec:
  project: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  source:
    repoURL: https://github.com/symmatree/tiles.git
    targetRevision: main
    path: tanka
    plugin:
      env:
        - name: TK_ENV
          value: kubernetes-mixin
      parameters:
        - name: cluster_name
          string: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
        - name: vault_name
          string: '{{ required ".Values.vault_name is required" .Values.vault_name }}'
        - name: project_id
          string: '{{ required ".Values.project_id is required" .Values.project_id }}'
        - name: app_settings
          map: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-mixin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
