# Started from
# https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/tags/external-dns-helm-chart-1.16.1/charts/external-dns/values.yaml

external-dns:
  serviceMonitor:
    enabled: true
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
  logFormat: text # @schema enum:["text", "json"]; type:string; default: "text"
  # -- Interval for DNS updates.
  interval: 1m
  # -- How DNS records are synchronized between sources and providers; available values are `sync` & `upsert-only`.
  policy: upsert-only # @schema enum:[sync, upsert-only]; type:string; default: "upsert-only"
  # -- Specify the registry for storing ownership and labels.
  # Valid values are `txt`, `aws-sd`, `dynamodb` & `noop`.
  registry: txt # @schema enum:[txt, aws-sd, dynamodb, noop]; default: "txt"
  # -- (string) Specify an identifier for this instance of _ExternalDNS_ wWhen using a registry other than `noop`.
  txtOwnerId: "placeholder-cluster-name"
  # -- Limit possible target zones by domain suffixes.
  domainFilters:
    - "placeholder-cluster-name.symmatree.com"
    - 0.10.in-addr.arpa
  provider:
    name: google
  extraArgs:
    - --google-project=placeholder-project-id
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/secrets/service-account/credential.json
  extraVolumeMounts:
    - name: google-service-account
      mountPath: /etc/secrets/service-account/
  extraVolumes:
    - name: google-service-account
      secret:
        secretName: clouddns-sa
