apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: lb-externalip-pool
spec:
  blocks:
    - cidr: "{{ .Values.external_ip_cidr }}"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: announce-everything
spec:
  # No serviceSelector, apply to all.
  # No nodeSelector, many of these run on the control plane anyway.
  # nodeSelector:
  #   matchExpressions:
  #     - key: node-role.kubernetes.io/control-plane
  #       operator: DoesNotExist
  externalIPs: true
  loadBalancerIPs: true
