apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
  labels:
    name: argocd-applications
spec:
  project: "{{ .Values.cluster_name }}"
  source:
    repoURL: https://github.com/symmatree/tiles.git
    targetRevision: "{{ .Values.targetRevision }}"
    path: charts/argocd-applications
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        # Propagate to other application.yaml files
        targetRevision: "{{ .Values.targetRevision }}"
        pod_cidr: "{{ .Values.pod_cidr }}"
        cluster_name: "{{ .Values.cluster_name }}"
        external_ip_cidr: "{{ .Values.external_ip_cidr }}"
        vault_name: "{{ .Values.vault_name }}"
        project_id: "{{ .Values.project_id }}"
        loki_bucket_chunks: "{{ .Values.loki_bucket_chunks }}"
        loki_bucket_ruler: "{{ .Values.loki_bucket_ruler }}"
        loki_bucket_admin: "{{ .Values.loki_bucket_admin }}"
        mimir_bucket_alertmanager: "{{ .Values.mimir_bucket_alertmanager }}"
        mimir_bucket_blocks: "{{ .Values.mimir_bucket_blocks }}"
        mimir_bucket_ruler: "{{ .Values.mimir_bucket_ruler }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
