targetRevision: placeholder-revision
pod_cidr: "placeholder-pod-cidr"
cluster_name: "placeholder-cluster-name"
external_ip_cidr: "placeholder-external-ip-cidr"
vault_name: "placeholder-vault-name"
project_id: "placeholder-project-id"
