apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter-mixin
  namespace: argocd
  labels:
    name: node-exporter-mixin
spec:
  project: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  source:
    repoURL: https://github.com/symmatree/tiles.git
    targetRevision: main
    path: tanka
    plugin:
      env:
        - name: TK_ENV
          value: node-exporter-mixin
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-mixin
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
