apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: clouddns-sa
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  # secret name is specified in tf/modules/k8s-cluster/external-dns.tf
  itemPath: vaults/{{ .Values.vault_name }}/items/{{ .Values.cluster_name }}-external-dns-clouddns-sa-key
