---
# Source: extract-apis/templates/capabilities.yaml.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-versions
data:
  api-versions.yaml: |
    APIVersions:
      - v1
      - admissionregistration.k8s.io/v1
      - admissionregistration.k8s.io/v1alpha1
      - admissionregistration.k8s.io/v1beta1
      - internal.apiserver.k8s.io/v1alpha1
      - apps/v1
      - apps/v1beta1
      - apps/v1beta2
      - authentication.k8s.io/v1
      - authentication.k8s.io/v1alpha1
      - authentication.k8s.io/v1beta1
      - authorization.k8s.io/v1
      - authorization.k8s.io/v1beta1
      - autoscaling/v1
      - autoscaling/v2
      - autoscaling/v2beta1
      - autoscaling/v2beta2
      - batch/v1
      - batch/v1beta1
      - certificates.k8s.io/v1
      - certificates.k8s.io/v1beta1
      - certificates.k8s.io/v1alpha1
      - coordination.k8s.io/v1alpha2
      - coordination.k8s.io/v1beta1
      - coordination.k8s.io/v1
      - discovery.k8s.io/v1
      - discovery.k8s.io/v1beta1
      - events.k8s.io/v1
      - events.k8s.io/v1beta1
      - extensions/v1beta1
      - flowcontrol.apiserver.k8s.io/v1
      - flowcontrol.apiserver.k8s.io/v1beta1
      - flowcontrol.apiserver.k8s.io/v1beta2
      - flowcontrol.apiserver.k8s.io/v1beta3
      - networking.k8s.io/v1
      - networking.k8s.io/v1beta1
      - node.k8s.io/v1
      - node.k8s.io/v1alpha1
      - node.k8s.io/v1beta1
      - policy/v1
      - policy/v1beta1
      - rbac.authorization.k8s.io/v1
      - rbac.authorization.k8s.io/v1beta1
      - rbac.authorization.k8s.io/v1alpha1
      - resource.k8s.io/v1
      - resource.k8s.io/v1beta2
      - resource.k8s.io/v1beta1
      - resource.k8s.io/v1alpha3
      - scheduling.k8s.io/v1alpha1
      - scheduling.k8s.io/v1beta1
      - scheduling.k8s.io/v1
      - storage.k8s.io/v1beta1
      - storage.k8s.io/v1
      - storage.k8s.io/v1alpha1
      - storagemigration.k8s.io/v1alpha1
      - apiextensions.k8s.io/v1beta1
      - apiextensions.k8s.io/v1
      - acme.cert-manager.io/v1
      - acme.cert-manager.io/v1/Challenge
      - acme.cert-manager.io/v1/Order
      - admissionregistration.k8s.io/v1
      - admissionregistration.k8s.io/v1/MutatingWebhookConfiguration
      - admissionregistration.k8s.io/v1/ValidatingAdmissionPolicy
      - admissionregistration.k8s.io/v1/ValidatingAdmissionPolicyBinding
      - admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration
      - apiextensions.k8s.io/v1
      - apiextensions.k8s.io/v1/CustomResourceDefinition
      - apiregistration.k8s.io/v1
      - apiregistration.k8s.io/v1/APIService
      - apps/v1
      - apps/v1/ControllerRevision
      - apps/v1/DaemonSet
      - apps/v1/Deployment
      - apps/v1/ReplicaSet
      - apps/v1/Scale
      - apps/v1/StatefulSet
      - argoproj.io/v1alpha1
      - argoproj.io/v1alpha1/AppProject
      - argoproj.io/v1alpha1/Application
      - argoproj.io/v1alpha1/ApplicationSet
      - authentication.k8s.io/v1
      - authentication.k8s.io/v1/SelfSubjectReview
      - authentication.k8s.io/v1/TokenReview
      - authorization.k8s.io/v1
      - authorization.k8s.io/v1/LocalSubjectAccessReview
      - authorization.k8s.io/v1/SelfSubjectAccessReview
      - authorization.k8s.io/v1/SelfSubjectRulesReview
      - authorization.k8s.io/v1/SubjectAccessReview
      - autoscaling/v1
      - autoscaling/v1/HorizontalPodAutoscaler
      - autoscaling/v2
      - autoscaling/v2/HorizontalPodAutoscaler
      - batch/v1
      - batch/v1/CronJob
      - batch/v1/Job
      - cert-manager.io/v1
      - cert-manager.io/v1/Certificate
      - cert-manager.io/v1/CertificateRequest
      - cert-manager.io/v1/ClusterIssuer
      - cert-manager.io/v1/Issuer
      - certificates.k8s.io/v1
      - certificates.k8s.io/v1/CertificateSigningRequest
      - cilium.io/v2
      - cilium.io/v2/CiliumCIDRGroup
      - cilium.io/v2/CiliumClusterwideEnvoyConfig
      - cilium.io/v2/CiliumClusterwideNetworkPolicy
      - cilium.io/v2/CiliumEndpoint
      - cilium.io/v2/CiliumEnvoyConfig
      - cilium.io/v2/CiliumIdentity
      - cilium.io/v2/CiliumLoadBalancerIPPool
      - cilium.io/v2/CiliumNetworkPolicy
      - cilium.io/v2/CiliumNode
      - cilium.io/v2/CiliumNodeConfig
      - cilium.io/v2alpha1
      - cilium.io/v2alpha1/CiliumCIDRGroup
      - cilium.io/v2alpha1/CiliumGatewayClassConfig
      - cilium.io/v2alpha1/CiliumL2AnnouncementPolicy
      - cilium.io/v2alpha1/CiliumLoadBalancerIPPool
      - cilium.io/v2alpha1/CiliumNodeConfig
      - cilium.io/v2alpha1/CiliumPodIPPool
      - coordination.k8s.io/v1
      - coordination.k8s.io/v1/Lease
      - discovery.k8s.io/v1
      - discovery.k8s.io/v1/EndpointSlice
      - events.k8s.io/v1
      - events.k8s.io/v1/Event
      - externaldns.k8s.io/v1alpha1
      - externaldns.k8s.io/v1alpha1/DNSEndpoint
      - flowcontrol.apiserver.k8s.io/v1
      - flowcontrol.apiserver.k8s.io/v1/FlowSchema
      - flowcontrol.apiserver.k8s.io/v1/PriorityLevelConfiguration
      - gateway.networking.k8s.io/v1
      - gateway.networking.k8s.io/v1/BackendTLSPolicy
      - gateway.networking.k8s.io/v1/GRPCRoute
      - gateway.networking.k8s.io/v1/Gateway
      - gateway.networking.k8s.io/v1/GatewayClass
      - gateway.networking.k8s.io/v1/HTTPRoute
      - gateway.networking.k8s.io/v1beta1
      - gateway.networking.k8s.io/v1beta1/Gateway
      - gateway.networking.k8s.io/v1beta1/GatewayClass
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
      - gateway.networking.k8s.io/v1beta1/ReferenceGrant
      - monitoring.coreos.com/v1
      - monitoring.coreos.com/v1/PodMonitor
      - monitoring.coreos.com/v1/Probe
      - monitoring.coreos.com/v1/PrometheusRule
      - monitoring.coreos.com/v1/ServiceMonitor
      - monitoring.coreos.com/v1alpha1
      - monitoring.coreos.com/v1alpha1/ScrapeConfig
      - networking.k8s.io/v1
      - networking.k8s.io/v1/IPAddress
      - networking.k8s.io/v1/Ingress
      - networking.k8s.io/v1/IngressClass
      - networking.k8s.io/v1/NetworkPolicy
      - networking.k8s.io/v1/ServiceCIDR
      - node.k8s.io/v1
      - node.k8s.io/v1/RuntimeClass
      - onepassword.com/v1
      - onepassword.com/v1/OnePasswordItem
      - policy/v1
      - policy/v1/PodDisruptionBudget
      - rbac.authorization.k8s.io/v1
      - rbac.authorization.k8s.io/v1/ClusterRole
      - rbac.authorization.k8s.io/v1/ClusterRoleBinding
      - rbac.authorization.k8s.io/v1/Role
      - rbac.authorization.k8s.io/v1/RoleBinding
      - resource.k8s.io/v1
      - resource.k8s.io/v1/DeviceClass
      - resource.k8s.io/v1/ResourceClaim
      - resource.k8s.io/v1/ResourceClaimTemplate
      - resource.k8s.io/v1/ResourceSlice
      - rollout-operator.grafana.com/v1
      - rollout-operator.grafana.com/v1/ReplicaTemplate
      - rollout-operator.grafana.com/v1/Scale
      - rollout-operator.grafana.com/v1/ZoneAwarePodDisruptionBudget
      - scheduling.k8s.io/v1
      - scheduling.k8s.io/v1/PriorityClass
      - storage.k8s.io/v1
      - storage.k8s.io/v1/CSIDriver
      - storage.k8s.io/v1/CSINode
      - storage.k8s.io/v1/CSIStorageCapacity
      - storage.k8s.io/v1/StorageClass
      - storage.k8s.io/v1/VolumeAttachment
      - storage.k8s.io/v1/VolumeAttributesClass
      - trust.cert-manager.io/v1alpha1
      - trust.cert-manager.io/v1alpha1/Bundle
      - v1
      - v1/Binding
      - v1/ComponentStatus
      - v1/ConfigMap
      - v1/Endpoints
      - v1/Event
      - v1/Eviction
      - v1/LimitRange
      - v1/Namespace
      - v1/Node
      - v1/NodeProxyOptions
      - v1/PersistentVolume
      - v1/PersistentVolumeClaim
      - v1/Pod
      - v1/PodAttachOptions
      - v1/PodExecOptions
      - v1/PodPortForwardOptions
      - v1/PodProxyOptions
      - v1/PodTemplate
      - v1/ReplicationController
      - v1/ResourceQuota
      - v1/Scale
      - v1/Secret
      - v1/Service
      - v1/ServiceAccount
      - v1/ServiceProxyOptions
      - v1/TokenRequest
    KubeVersion:
      Major: "1"
      Minor: "34"
      Version: v1.34
