---
# Source: extract-apis/templates/capabilities.yaml.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-versions
data:
  api-versions.yaml: |
    APIVersions:
      - gateway.networking.k8s.io/v1/GRPCRoute
      - v1/ResourceQuota
      - authorization.k8s.io/v1
      - batch/v1/CronJob
      - acme.cert-manager.io/v1/Challenge
      - argoproj.io/v1alpha1/AppProject
      - gateway.networking.k8s.io/v1/HTTPRoute
      - policy/v1
      - monitoring.coreos.com/v1
      - storage.k8s.io/v1/VolumeAttributesClass
      - cilium.io/v2alpha1
      - v1/ReplicationController
      - networking.k8s.io/v1/ServiceCIDR
      - rbac.authorization.k8s.io/v1/RoleBinding
      - apiextensions.k8s.io/v1/CustomResourceDefinition
      - node.k8s.io/v1/RuntimeClass
      - argoproj.io/v1alpha1/Application
      - v1/TokenRequest
      - policy/v1/PodDisruptionBudget
      - discovery.k8s.io/v1/EndpointSlice
      - trust.cert-manager.io/v1alpha1/Bundle
      - apps/v1/StatefulSet
      - autoscaling/v1/HorizontalPodAutoscaler
      - cert-manager.io/v1/Issuer
      - gateway.networking.k8s.io/v1/Gateway
      - autoscaling/v2
      - cilium.io/v2/CiliumCIDRGroup
      - cilium.io/v2/CiliumEndpoint
      - v1/Binding
      - v1/Event
      - authorization.k8s.io/v1/SelfSubjectRulesReview
      - certificates.k8s.io/v1/CertificateSigningRequest
      - cert-manager.io/v1/CertificateRequest
      - onepassword.com/v1/OnePasswordItem
      - networking.k8s.io/v1/IngressClass
      - resource.k8s.io/v1/DeviceClass
      - cilium.io/v2/CiliumNodeConfig
      - rbac.authorization.k8s.io/v1
      - apiextensions.k8s.io/v1
      - node.k8s.io/v1
      - gateway.networking.k8s.io/v1/BackendTLSPolicy
      - gateway.networking.k8s.io/v1beta1/Gateway
      - rbac.authorization.k8s.io/v1/ClusterRole
      - admissionregistration.k8s.io/v1/ValidatingAdmissionPolicyBinding
      - coordination.k8s.io/v1/Lease
      - gateway.networking.k8s.io/v1beta1/ReferenceGrant
      - resource.k8s.io/v1
      - onepassword.com/v1
      - v1/Pod
      - batch/v1/Job
      - storage.k8s.io/v1/CSINode
      - storage.k8s.io/v1/CSIStorageCapacity
      - cilium.io/v2alpha1/CiliumL2AnnouncementPolicy
      - v1
      - gateway.networking.k8s.io/v1beta1
      - cilium.io/v2/CiliumNetworkPolicy
      - apps/v1/ControllerRevision
      - authorization.k8s.io/v1/LocalSubjectAccessReview
      - rbac.authorization.k8s.io/v1/ClusterRoleBinding
      - flowcontrol.apiserver.k8s.io/v1/FlowSchema
      - apiregistration.k8s.io/v1
      - cilium.io/v2alpha1/CiliumGatewayClassConfig
      - monitoring.coreos.com/v1alpha1/ScrapeConfig
      - rollout-operator.grafana.com/v1/ReplicaTemplate
      - rollout-operator.grafana.com/v1/ZoneAwarePodDisruptionBudget
      - v1/PodExecOptions
      - v1/PodPortForwardOptions
      - resource.k8s.io/v1/ResourceClaim
      - externaldns.k8s.io/v1alpha1
      - gateway.networking.k8s.io/v1
      - v1/Service
      - apps/v1/DaemonSet
      - cilium.io/v2/CiliumEnvoyConfig
      - authentication.k8s.io/v1
      - admissionregistration.k8s.io/v1
      - coordination.k8s.io/v1
      - v1/Endpoints
      - storage.k8s.io/v1/CSIDriver
      - cilium.io/v2/CiliumClusterwideNetworkPolicy
      - flowcontrol.apiserver.k8s.io/v1
      - monitoring.coreos.com/v1alpha1
      - admissionregistration.k8s.io/v1/ValidatingAdmissionPolicy
      - cilium.io/v2/CiliumClusterwideEnvoyConfig
      - monitoring.coreos.com/v1/PrometheusRule
      - rollout-operator.grafana.com/v1/Scale
      - acme.cert-manager.io/v1
      - v1/PersistentVolume
      - v1/PodProxyOptions
      - v1/ServiceProxyOptions
      - apps/v1/Deployment
      - authentication.k8s.io/v1/TokenReview
      - scheduling.k8s.io/v1/PriorityClass
      - apps/v1
      - autoscaling/v1
      - argoproj.io/v1alpha1
      - networking.k8s.io/v1/IPAddress
      - resource.k8s.io/v1/ResourceClaimTemplate
      - cilium.io/v2/CiliumIdentity
      - cilium.io/v2/CiliumNode
      - gateway.networking.k8s.io/v1/GatewayClass
      - events.k8s.io/v1
      - v1/PersistentVolumeClaim
      - networking.k8s.io/v1/NetworkPolicy
      - storage.k8s.io/v1/StorageClass
      - cilium.io/v2alpha1/CiliumPodIPPool
      - monitoring.coreos.com/v1/Probe
      - v1/Scale
      - externaldns.k8s.io/v1alpha1/DNSEndpoint
      - monitoring.coreos.com/v1/PodMonitor
      - v1/NodeProxyOptions
      - storage.k8s.io/v1/VolumeAttachment
      - admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration
      - argoproj.io/v1alpha1/ApplicationSet
      - cilium.io/v2/CiliumLoadBalancerIPPool
      - cilium.io/v2alpha1/CiliumNodeConfig
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
      - discovery.k8s.io/v1
      - v1/ComponentStatus
      - apiregistration.k8s.io/v1/APIService
      - networking.k8s.io/v1/Ingress
      - admissionregistration.k8s.io/v1/MutatingWebhookConfiguration
      - v1/PodAttachOptions
      - trust.cert-manager.io/v1alpha1
      - resource.k8s.io/v1/ResourceSlice
      - cert-manager.io/v1/Certificate
      - monitoring.coreos.com/v1/ServiceMonitor
      - v1/PodTemplate
      - batch/v1
      - certificates.k8s.io/v1
      - v1/Node
      - v1/ServiceAccount
      - authorization.k8s.io/v1/SubjectAccessReview
      - rollout-operator.grafana.com/v1
      - apps/v1/Scale
      - autoscaling/v2/HorizontalPodAutoscaler
      - rbac.authorization.k8s.io/v1/Role
      - flowcontrol.apiserver.k8s.io/v1/PriorityLevelConfiguration
      - cert-manager.io/v1
      - v1/LimitRange
      - v1/Namespace
      - v1/Eviction
      - authorization.k8s.io/v1/SelfSubjectAccessReview
      - gateway.networking.k8s.io/v1beta1/GatewayClass
      - scheduling.k8s.io/v1
      - cert-manager.io/v1/ClusterIssuer
      - cilium.io/v2alpha1/CiliumCIDRGroup
      - cilium.io/v2alpha1/CiliumLoadBalancerIPPool
      - networking.k8s.io/v1
      - apps/v1/ReplicaSet
      - events.k8s.io/v1/Event
      - v1/ConfigMap
      - storage.k8s.io/v1
      - cilium.io/v2
      - v1/Secret
      - authentication.k8s.io/v1/SelfSubjectReview
      - acme.cert-manager.io/v1/Order
    KubeVersion:
      Major: "1"
      Minor: "34"
      Version: v1.34.0
    HelmVersion:
      git_commit: 99cd1964357c793351be481d55abbe21c6b2f4ec
      git_tree_state: clean
      go_version: go1.25.4
      kube_client_version: v1.34
      version: v4.0.0
