apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cert-manager-dns01-sa-key
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  # secret name is specified in tf/modules/k8s-cluster/k8s-cert-manager.tf
  itemPath: vaults/{{ .Values.vault_name }}/items/{{ .Values.cluster_name }}-cert-manager-dns01-sa-key
