apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-cert
  namespace: "{{ .Release.Namespace }}"
spec:
  acme:
    email: symmetry@pobox.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-staging
    solvers:
      - selector:
          dnsZones:
            - "{{ .Values.cluster_name }}.symmatree.com"
        dns01:
          cloudDNS:
            project: "{{ .Values.project_id }}"
            serviceAccountSecretRef:
              name: misc-config
              key: cert_manager_clouddns_sa
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: real-cert
spec:
  acme:
    email: symmetry@pobox.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-real
    solvers:
      - selector:
          dnsZones:
            - "{{ .Values.cluster_name }}.symmatree.com"
        dns01:
          cloudDNS:
            project: "{{ .Values.project_id }}"
            serviceAccountSecretRef:
              name: misc-config
              key: cert_manager_clouddns_sa
