apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ .Values.cluster_name }}-selfsigned-root"
  namespace: "{{ .Release.Namespace }}"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.cluster_name }}-ca"
  namespace: cert-manager
spec:
  isCA: true
  commonName: "{{ .Values.cluster_name }}-ca"
  subject:
    organizations:
      - "{{ .Values.cluster_name }}"
    organizationalUnits:
      - "{{ .Values.cluster_name }}"
  secretName: tales-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: "{{ .Values.cluster_name }}-selfsigned-root"
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ .Values.cluster_name }}-ca-issuer"
spec:
  ca:
    secretName: "{{ .Values.cluster_name }}-ca-tls"
