apiVersion: v2
name: mimir
description: mimir
type: application
version: 0.1.0
appVersion: 3.0.1
dependencies:
  - name: mimir-distributed
    version: 6.0.5
    repository: https://grafana.github.io/helm-charts
