# Values for templates/
cluster_name: placeholder-cluster-name
vault_name: placeholder-vault-name

# From
# https://raw.githubusercontent.com/cert-manager/cert-manager/refs/tags/v1.17.1/deploy/charts/cert-manager/values.yaml
# keeping only values we override (or want to).
cert-manager:
  global:
    # The number of old ReplicaSets to retain to allow rollback (if not set, the default Kubernetes value is set to 10).
    # +docs:property
    revisionHistoryLimit: 1
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
  crds:
    enabled: false
    keep: true
  # When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted.
  enableCertificateOwnerRef: true
  config:
    enableGatewayAPI: true
  # Configure DNS-01 challenge propagation checks to use external DNS servers
  # instead of localhost (127.0.0.1:53) which isn't available in Cilium/Talos setups
  extraArgs:
    - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  prometheus:
    servicemonitor:
      # Create a ServiceMonitor to add cert-manager to Prometheus.
      enabled: true
  webhook:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: ""
  cainjector:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: ""
  startupapicheck:
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: ""
trust-manager:
  # The trust-manager has a webhook so really useful to have it on control plane.
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
  secretTargets:
    enabled: true
    authorizedSecrets:
      - "placeholder-authorized-secret"
