apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: loki-tenant-auth
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: vaults/{{ .Values.vault_name }}/items/{{ .Values.cluster_name }}-loki-tenant-auth
