name: "nodes-plan-apply"
on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Whether to apply the plan after creating it'
        required: false
        default: 'false'
  pull_request: {}
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 2 * * *" # Daily at 0200 UTC

env:
  TF_IN_AUTOMATION: "true"
  TF_VAR_onepassword_sa_token: ${{ secrets.ONEPASSWORD_SA_TOKEN }}
concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false
jobs:
  nodes-plan-apply:
    # runs-on: "ubuntu-latest"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: "read"
      id-token: "write"
      issues: "write"
      pull-requests: "write"

    steps:
      - name: DateAndTimeStamps
        id: stamps
        run: |
          set -euo pipefail
          timestamp=$(date +'%Y%m%dT%H%M%S')
          datestamp=$(date +'%Y%m%d')
          echo "TIMESTAMP=${timestamp}" | tee -a "$GITHUB_OUTPUT"
          echo "DATESTAMP=${datestamp}" | tee -a "$GITHUB_OUTPUT"
      - uses: "actions/checkout@v5"
      - uses: "hashicorp/setup-terraform@v3"
        with:
          terraform_version: "1.13.3"

      - name: Load secrets
        id: load_secrets
        uses: 1password/load-secrets-action@v3
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONEPASSWORD_SA_TOKEN }}
          GCP_TILES_TF_SA_EMAIL: "op://tiles-secrets/gcp_tiles_tf_sa/username"
          GCP_TILES_TF_SA_KEY: "op://tiles-secrets/gcp_tiles_tf_sa/password"
          # TILES_VPN_CONFIG: "op://tiles-secrets/github-vpn-config/wireguard-config"
          VPN_PRIVATE_KEY: "op://tiles-secrets/github-vpn-client/private-key"
          VPN_PUBLIC_KEY: "op://tiles-secrets/github-vpn-client/public-key"
          VPN_ENDPOINT: "op://tiles-secrets/github-vpn-client/endpoint"

      - name: Authenticate to Google Cloud
        run: |
          set -euo pipefail
          echo '${{ steps.load_secrets.outputs.GCP_TILES_TF_SA_KEY }}' > "${RUNNER_TEMP}/gcp-sa-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${RUNNER_TEMP}/gcp-sa-key.json" >> "$GITHUB_ENV"
          echo "GOOGLE_CLOUD_PROJECT=${{ secrets.PROJECT_ID }}" >> "$GITHUB_ENV"

      - name: Terraform cache
        id: tf-cache
        uses: actions/cache@v4
        with:
          path: |
            **/.terraform
          # Use date so we refetch once a day no matter what.
          key: ${{ runner.os }}-tools-${{ steps.stamps.outputs.DATESTAMP }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tools-${{ steps.stamps.outputs.DATESTAMP }}-
            ${{ runner.os }}-tools-

      - name: Terraform init
        if: steps.tf-cache.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}/tf/nodes"
          terraform init

      - uses: ./.github/actions/wireguard
        name: Wireguard
        id: wireguard
        with:
          # vpn_config: ${{ steps.load_secrets.outputs.VPN_CONFIG }}
          conf_dir: "${{ runner.temp }}/wg"
          private_key: ${{ steps.load_secrets.outputs.VPN_PRIVATE_KEY }}
          public_key: ${{ steps.load_secrets.outputs.VPN_PUBLIC_KEY }}
          endpoint: ${{ steps.load_secrets.outputs.VPN_ENDPOINT }}
          allowed_ips: 0.0.0.0/0
          client_ip: 10.1.0.4
          gateway_ip: 10.1.0.1

      - name: DNS debug
        run: |
          set -euxo pipefail
          echo "=== network interfaces ==="
          cat /etc/network/interfaces || true
          echo "=== resolv.conf ==="
          cat /etc/resolv.conf || true

          echo "=== ip route show ==="
          sudo ip route show

          echo "=== resolvectl status ==="
          resolvectl status
          echo "=== manual nslookup ==="
          echo "Default dns"
          nslookup nuc-g3p-1.local.symmatree.com || true
          echo "Force 10.0.99.1"
          nslookup nuc-g3p-1.local.symmatree.com 10.0.99.1 || true

          # echo "Setting DNS to 10.0.99.1"
          # sudo resolvectl dns wg0 10.0.99.1%wg0
          # sudo resolvectl domain wg0 symmatree.com
          # sudo resolvectl default-route wg0 true

          echo "=== resolvectl status ==="
          resolvectl status
          echo "=== manual nslookup ==="
          echo "Default dns"
          nslookup nuc-g3p-1.local.symmatree.com || true
          echo "Force 10.0.99.1"
          nslookup nuc-g3p-1.local.symmatree.com 10.0.99.1 || true


      - name: Terraform plan nodes
        id: tf-plan
        env:
          PLAN_FILE: "${{ runner.temp }}/tfplan-nodes-${{ steps.stamps.outputs.TIMESTAMP }}.bin"
        shell: bash
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}/tf/nodes"
          mkdir -p "${{ runner.temp }}/txt-outputs"
          terraform plan -lock-timeout=5m -input=false -out="${PLAN_FILE}"
          terraform show -no-color "${PLAN_FILE}" \
            > "${{ runner.temp }}/txt-outputs/plan-nodes-${{ steps.stamps.outputs.TIMESTAMP }}.txt"

      - name: Terraform apply nodes
        id: tf-apply
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event.inputs.apply == 'true')
        env:
          PLAN_FILE: "${{ runner.temp }}/tfplan-nodes-${{ steps.stamps.outputs.TIMESTAMP }}.bin"
        shell: bash
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}/tf/nodes"
          echo "Applying plan"
          terraform apply -lock-timeout=5m "${PLAN_FILE}"

      - uses: ./.github/actions/attach-outputs
        name: Attach outputs to PR
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          txt_output_dir: "${{ runner.temp }}/txt-outputs/"
          outcome: ${{ steps.tf-plan.outcome }}
