name: "nodes-plan-apply"
on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Whether to apply the plan after creating it"
        type: boolean
        default: false
  pull_request: {}
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 8 * * *" # Daily at 0800 UTC

env:
  TF_IN_AUTOMATION: "true"
  TF_VAR_onepassword_sa_token: ${{ secrets.ONEPASSWORD_SA_TOKEN }}
concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false
jobs:
  nodes-plan-apply:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
      issues: "write"
      pull-requests: "write"

    steps:
      - name: DateAndTimeStamps
        id: stamps
        run: |
          set -euo pipefail
          timestamp=$(date +'%Y%m%dT%H%M%S')
          datestamp=$(date +'%Y%m%d')
          echo "TIMESTAMP=${timestamp}" | tee -a "$GITHUB_OUTPUT"
          echo "DATESTAMP=${datestamp}" | tee -a "$GITHUB_OUTPUT"
      - uses: "actions/checkout@v6"
      - uses: "hashicorp/setup-terraform@v3"
        with:
          terraform_version: "1.13.3"

      - name: Load secrets
        id: load_secrets
        uses: 1password/load-secrets-action@v3
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONEPASSWORD_SA_TOKEN }}
          GCP_TILES_TF_SA_EMAIL: "op://tiles-secrets/gcp_tiles_tf_sa/username"
          GCP_TILES_TF_SA_KEY: "op://tiles-secrets/gcp_tiles_tf_sa/password"
          TILES_VPN_CONFIG: "op://tiles-secrets/github-vpn-client/notesPlain"

      - name: Authenticate to Google Cloud
        run: |
          set -euo pipefail
          echo '${{ steps.load_secrets.outputs.GCP_TILES_TF_SA_KEY }}' > "${RUNNER_TEMP}/gcp-sa-key.json"
          PROJECT_ID=$(jq -r '.project_id' "${RUNNER_TEMP}/gcp-sa-key.json")
          {
            echo "GOOGLE_APPLICATION_CREDENTIALS=${RUNNER_TEMP}/gcp-sa-key.json";
            echo "GOOGLE_CLOUD_PROJECT=${PROJECT_ID}";
            echo "project_id=${PROJECT_ID}";
          }>> "$GITHUB_ENV";

      - name: Terraform cache
        id: tf-cache
        uses: actions/cache@v4
        with:
          path: |
            **/.terraform
          # Use date so we refetch once a day no matter what.
          key: ${{ runner.os }}-tf-${{ steps.stamps.outputs.DATESTAMP }}-${{ hashFiles('**/.terraform.lock.hcl', 'tf-cache-poison.txt') }}
          restore-keys: |
            ${{ runner.os }}-tf-${{ steps.stamps.outputs.DATESTAMP }}-

      - name: Terraform init
        if: steps.tf-cache.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}/tf/nodes"
          terraform init

      - uses: ./.github/actions/wg-quick
        id: wireguard
        with:
          wg_config: ${{ steps.load_secrets.outputs.TILES_VPN_CONFIG }}
          conf_dir: "$HOME"

      - name: Terraform plan nodes
        id: tf-plan
        env:
          PLAN_FILE: "${{ runner.temp }}/tfplan-nodes-${{ steps.stamps.outputs.TIMESTAMP }}.bin"
        shell: bash
        run: |
          set -euo pipefail
          echo "::notice title=Terraform::$(terraform version)"
          cd "${GITHUB_WORKSPACE}/tf/nodes"
          mkdir -p "${{ runner.temp }}/txt-outputs"
          terraform plan -lock-timeout=5m -input=false -out="${PLAN_FILE}"
          terraform show -no-color "${PLAN_FILE}" \
            > "${{ runner.temp }}/txt-outputs/plan-nodes-${{ steps.stamps.outputs.TIMESTAMP }}.txt"

      - name: Terraform apply nodes
        id: tf-apply
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event.inputs.apply == 'true')
        env:
          PLAN_FILE: "${{ runner.temp }}/tfplan-nodes-${{ steps.stamps.outputs.TIMESTAMP }}.bin"
        shell: bash
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}/tf/nodes"
          echo "Applying plan"
          terraform apply -lock-timeout=5m "${PLAN_FILE}"

      - name: Install helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: "v4.0.0"

      - name: Regenerate API versions
        shell: bash
        run: |
          set -euo pipefail
          # TODO: Install yq properly with caching and versioning.
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

          ./charts/extract-apis/generate-api-versions.sh
          # Check for changes (warn only, don't fail)
          if ! git diff --exit-code ; then
            echo "::warning title=API Versions Changed::API versions or kube version have changed. Consider committing the updated files."
            git diff charts/extract-apis/helm-api-versions.txt charts/extract-apis/helm-kube-version.txt
          fi

      - name: De-wireguard
        if: always()
        run: |
          set -euo pipefail
          if [ -z "${{ steps.wireguard.outputs.wg_connected }}" ]; then
            echo "No Wireguard connection established, skipping disconnection."
            exit 0
          fi
          echo "Disconnecting Wireguard..."
          time sudo wg-quick down "$HOME/wg0.conf" || true
          echo "Disconnected"

      - uses: ./.github/actions/attach-outputs
        name: Attach outputs to PR
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          txt_output_dir: "${{ runner.temp }}/txt-outputs/"
          outcome: ${{ steps.tf-plan.outcome }}
